Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Stlye/WordArray:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/AlignParameters:
  Enabled: false
