root to: 'home#login'
post '/items', to: 'items#create'
post '/lists', to: 'lists#create'
post '/items/delete', to: 'items#delete'
post '/lists/delete', to: 'lists#delete'
get '/users/signup', to: 'users#signup'
post '/users/signup', to: 'users#signup'
post '/users', to: 'users#create'
get '/sessions/new', to: 'sessions#new'
post '/sessions/new', to: 'sessions#new'
post '/sessions', to: 'sessions#create'
delete '/sessions/logout', to: 'sessions#destroy'
post '/sessions/logout', to: 'sessions#destroy'
get '/home/index', to: 'home#index'
